public class logicChessData
{
    public static string[] BlanMssngvWls = {
        "Rene|9",
        "+b.|(She seems annoyed at herself.)",
        "-w_02|I can't believe I almost blew up during that bomb.|w|p|What happened exactly?",
        "+w.|Can you tell me what happened during the bomb that's making you so annoyed?",
        "-w.|Annoyed? What do you mean annoyed?! I did manage to solo the bomb y'know!",
        "+b_0508|(She's known for being good at soloing however making a mistake gets on her nerves.)|br|bp|I don't believe you soloed the bomb!|Wait and see.",
        "+w,|I'm sorry but I refuse to believe that soloing that challenge bomb is possible.",
        "-w,|Do you know who I am!? I've defused a bunch of bombs, strike free!",
        "+wX08|Nnnghhh!",
        "-w.|The one thing I struck on was Mssngv Wls. The first module was obviously Painting, which rules out A and I.",
        "-w.|The second module must've been Meteor, which rules out E and O. That means the missing vowel is U.",
        "-w.|The missing hieroglyph was Lion, and therefore Two Reeds must've been right, but it wasn't.",
        "-w.|After that I just started guessing as there was only one other module left.",
        "+w.|I believe I understand your situation now, thank you for sharing that.",
        "-w_142017|Wait... did I really say all that out loud? I thought all of that was in my head.|bbb|bnr|Are you sure that there was 'Painting'?|Are you sure that there was 'Meteor'?|Are you sure you identified the right module?",
        "+w,|Ivy Rene, you claim that the first module name that appeared was Painting, correct?",
        "-w,|What do you mean \"I claim\"? I know it was Painting! No other modules at the time of release would work...",
        "+wX13|Agh! You got a point there...",
        "+w,|You claim you were looking at Mssngv Wls, if I recall correctly. However I'm certain you were looking at--",
        "-w,|What are you talking about? Despite your name, you likely are not aware that Only Connect has 2 stages.",
        "+wX13|Wait, what?!",
        "+w.|Ah, I see what you must've gotten wrong. You claim that the second module name was Meteor, correct?",
        "-w.|Yep, that's what came to mind.",
        "+w.|I know for certain that what appeared could not have been Meteor.",
        "-w.|Wait, how so?",
        "+w.|The manual for Mssngv Wls states that the module shows the name of a module released before March 2021. ",
        "-w.|Wait a minute...",
        "+w.|Where you can clearly see that Meteor was released in April of that year, meaning it is not included.",
        "-w.|Ah shoot, the module was Meter, wasn't it... darn.",
        "+w!|I can confirm the only module it could have been was Meter."
    };
    public static string[] BlanRoundKeypad = {
        "ROB|1",
        "-w.|Hey Mr. Edgework!",
        "+b_02|(ROB is nice, almost too nice. I wonder what he wants.)|w|p|What's up?",
        "+w.|Hey ROB, nice to see you.",
        "-w.|Um I've got a question for you...",
        "+w.|Oh, you do?",
        "-w.|Yeah I was on Twitch Plays a while ago and everyone got mad at me for blowing up the bomb.",
        "*w.|I'm sorry to hear that, but that's not a question.",
        "-w_1108|Oh my bad, can I ask you how I struck on Round Keypad?|br|nq|Of course I can!|Round Keypad doesn't exist.",
        "*w,|ROB, I'm pretty sure there's no such thing as Round Keypad.",
        "-w,|Have you been living under a rock, Edgework? That module has been out for years!",
        "*bX11|(How have I been bested by the Banana guy?!)",
        "*w.|What happened that caused the strike to occur?",
        "-w.|Aight, so the symbols were forward Charlie, loop-de-loop, both hollow and filled stars, Omega, Lambda...",
        "-w.|...upside-down question mark, and my personal favorite, the smiley face.",
        "*w.|Okay, we now know what's on the module, what did you do then?",
        "-w.|I noticed that the 2nd, 3rd, and 5th columns were tied.",
        "-w.|I used that rule in the manual and sent a command which pressed seven buttons.",
        "-w.|Then the bomb blew up, and I don't know why.",
        "*b_261922|(Hmmm... where did ROB go wrong?)|bbb|rbp|The column used was incorrect.|Those symbols are from the wrong module.|I think you missed a symbol.",
        "*w,|Those symbols you read out, they don't appear to be from Round Keypad.",
        "-w,|Did you even LOOK at the manual you dunce?",
        "*wX18|What on earth was I thinking?!",
        "*w,|I think you missed a symbol on the keypad.",
        "-w,|I don't think I did, but let's count them!",
        "-w,|1, 2, 3, 4, 5, 6, 7... 8. There are 8 symbols, dude.",
        "*bX18|(Round Keypad is a lot harder that I thought...!)",
        "*w.|Ah, I see what happened. You excluded the symbols from the wrong column.",
        "-w.|Wait, what?",
        "*w.|When it says \"right-most column\" in the manual, it means the rightmost of the TIED columns.",
        "-w.|Y'know what now that you said it out loud that makes a lot more sense, thanks!",
        "*w.|Happy to help, ROB.",
        "*b!|(That manual is somewhat ambiguous but it's so old I think we'll cut the manual some slack...)"
    };
    public static string[] BlanHeartFMN = {
        "Kokoro|4",
        "-w_01|Yo.|w|p|What's up?",
        "*w.|How's it going?",
        "-w.|Not that well to be honest, we had to get rid of a really good bomb attempt after missing a Forget Me Not stage.",
        "*b.|(Missing a Forget Me Not stage? This is quite unusual given how often he defuses.)",
        "-w_0805|And I have absolutely no idea how I skipped a stage.|br|nr|I'll help you figure it out.|Who cares.",
        "*w,|Eh, who cares? It's not likely you'll run into that again.",
        "-w,|I'm sorry but last time I checked, missing a stage is unacceptable. I must figure out what went wrong.",
        "*bX08|(I can't let Edgework's family name be associated with my stupidity...!)",
        "*w.|Alright, let's take a look at the logfile...",
        "-w.|It says we also had an IPA, Splitting the Loot, The Heart, Silenced Simon, Stained Glass, Logic Gates...",
        "*w.|That is... a selection of modules.",
        "-w.|...and that's it really.",
        "*b_131721|(Must've been one of the bombs in an endurance run. At least there's not many possibilities.)|bbb|bqr|You had an ignored module on the bomb.|Are you sure it wasn't Forget Us Not?|A module solved without your knowledge.",
        "*w,|Ah, I see. You had an ignored module on the bomb.",
        "-w,|Uhhh, you sure? I'm fairly certain none of them are ignored but feel free to check.",
        "*b,|(Okay, let's take a look...)",
        "*bX12|(...darn. he's right. None of these are ignored.)",
        "*w,|Hmmm, I think the only possible option is that the Forget Me Not was actually a Forget Us Not.",
        "-w,|Are you kidding? You really thought that I'd mix the two up?!",
        "*w,|Uh... yeah I was kidding!",
        "*bX12|(...he's not falling for that one is he.)",
        "*w.|Ah, I know. A module must've solved without you realizing it.",
        "-w.|And what would that be, Edgework?",
        "*w.|The Heart. Yeah it's one of those pseudo-needies that isn't ignored by bosses.",
        "-w.|Ah, yeah that makes a lot of sense.",
        "*w.|Happy to help!",
        "-w!|I'll make sure to keep an eye on The Heart next time."
    };

    public static string[] BlanKeypadDirectionality = {
        "Interpret|2",
        "*b.|(Oh, it's Mr. Interpret.)",
        "-w_02|Hi, Mr. Edgework. Can I ask you about something that happened to me recently?|w|p|Of course!",
        "*w.|Sure, what ended up happening?",
        "-w.|So, me and my friends were doing a random freeplay bomb, we hadn't done those in a while.",
        "*b.|(Now that you bring it up I haven't done a freeplay bomb in a long time...)",
        "-w_0906|We had a Keypad Directionality module on the bomb. Do you know that module, Edgework?|br|bn|Yes, I do know Keypad Directionality.|No, I don't.",
        "*w.|No, I don't.",
        "-w.|Oh, that's fine. Luckily the manual isn't that long.",
        "*b.|(The first page is full of text, that being said though I've read worse.)",
        "*w.|Uh, yeah I know Keypad Directionality. But what happened exactly?",
        "-w.|Oh, right. Sorry. I'm fairly certain I got every single stage wrong...",
        "*w.|All of them? Interesting...",
        "-w.|The first stage should be enough to figure out what I messed up, right?",
        "*w.|I mean it's all the data you have, right?",
        "-w.|How'd you know?",
        "-w.|Anyway the starting number was 5, and the directions were up, up-right, up-left, down.",
        "-w.|And I got 8352 as the answer for that stage.",
        "*w.|Ah, okay. I see what happened.",
        "-w_271922|You do? Well if so what number should have been the answer?|bbb|bqr|2958|8152|2318",
        "*w,|I believe it would be 8152.",
        "-w,|That doesn't sound right, it's very similar to my answer.",
        "*bX18|(Looks like I made the same mistake!)",
        "*w,|It has to be 2318.",
        "-w,|I... don't see how that can possibly be right.",
        "*w,|Oh?",
        "-w,|Yeah you have to move across the keypad in those directions.",
        "*wX18|Oh... you're right. Darn.",
        "*w.|Ah, I know the answer. But before I answer your question, may I ask you a question?",
        "-w.|Uhhh... sure.",
        "*w.|Were you looking down at your keyboard when you were experting this?",
        "-w.|I don't see how that matters but yeah, I was.",
        "*w.|As you can see in the top-right image of the module, the numbers on the keypad are in order...",
        "*w.|...and those that are on your keyboard are vertically flipped.",
        "-w.|Oh, okay. I'll write a note saying not to look down at my keyboard when I do this.",
        "*b!|(He doesn't need to look down at the keyboard much to begin with.)"
    };

    public static string[] BlanIceCream = {
        "Min|6",
        "*w.|Hello there.",
        "-w_02|Oh hey, I've heard of you before. You're Mr. Edgework, right?|w|p|Indeed I am.",
        "*w.|Yes I am, nice to meet you. Do you need me for something?",
        "-w.|Yeah actually, isn't it your job to help figure out stuff?",
        "*w.|Pretty much, yeah.",
        "-w.|Can you figure out why I blew up the bomb to Ice Cream?",
        "*w.|Of course I can, I'm very familiar with Ice Cream.",
        "*b_1208|(Both the module and the food, ice cream is delicious. Let's not think about the food too much though.)|br|nk|Can you tell me what happened?|I'm gonna go get some ice cream.",
        "*w,|Y'know what this talk about ice cream makes me really want some. You mind if I get some?",
        "-w,|Now's not the time for clowning around, Edgework.",
        "*w,|Ah yeah, sorry.",
        "*bX12|(He's got a point. Didn't I just say not to think about the food too much?)",
        "*w.|Can you tell me the details?",
        "-w.|Sure, first things first, we were on the last stage, but we only had just over a minute left so we had to hurry.",
        "-w.|The last digit of the Serial Number was a 2, and the customer was Simon. Meaning allergies are \"1-6-4\".",
        "*w.|And what does that mean exactly?",
        "-w.|That means we can't give Simon strawberry, cookies, or fruit flavors. ",
        "*w.|Alright, go on.",
        "-w.|We had more unlit indicators than lit, so it's not the first list, however we do have an empty port plate.",
        "*w.|Okay, so the second list is used.",
        "-w.|For flavors on the module, we have Tutti Frutti, Raspberry Ripple, Double Strawberry, The Classic, and--",
        "*w.|You can stop there, I know the last one's Vanilla.",
        "-w_233227|Okay well the fact remains that Vanilla was the wrong answer. But I don't see how that can be.|bbb|nbr|You had the wrong allergies.|You submitted on an odd minute.|You gave Simon the wrong flavor.",
        "*w,|Ah, I see, you got the allergies wrong.",
        "-w,|Uh, really?",
        "*w,|According to info you gave me, the intersection of 2 and Simon in the table is... \"1-6-4\".",
        "*bX22|(Exactly what he gave me, darn.)",
        "*w,|It's quite simple: Vanilla was incorrect.",
        "-w,|Then what flavor could it have possibly been?",
        "*w,|Let's see... No fruit. Oh wait a minute...",
        "-w,|They all have fruit dude.",
        "*wX22|Gahh!",
        "*w.|Oh, I see. It's a very common mistake. You submitted on an odd minute.",
        "-w.|Ah wait... I did.",
        "*w.|The manual states \"Selling ice cream on an odd-numbered minute causes a strike.\"",
        "-w.|I don't think you need to rub in it like that, I already read the manual.",
        "*w.|Whoops, that wasn't what I intended. I apologize.",
        "-w!|It's alright."
    };

    public static string[] BlanTwoBits = {
        "Zebe|5",
        "-w_01|He-- Hello?|w|p|Hello.",
        "*w.|Hi there, how's it going?",
        "-w.|I've been doing well... mostly.",
        "*w.|Mostly?",
        "-w.|I recently got a strike on Two Bits.",
        "*w.|Luckily for you Two Bits is one of my favorites, I can help you sort this out.",
        "-w.|How'd you figure out that I didn't know how I struck?",
        "*w.|Well, if you knew why you struck you wouldn't be asking me, now would you?",
        "-w_0920|Yeah, right.|br|kq|Tell me what you did.|Let me just guess what happened.",
        "*w.|Can you tell me exactly what occurred?",
        "-w.|Sure thing, sir.",
        "-w.|Edgework was 3 batteries in 3 holders, unlit CAR, and RCA on one plate...",
        "-w.|...Serial Number was ZK7LW0.",
        "*w.|Yep, go on...",
        "-w.|I then went on to do Charlie Victor query.",
        "-w.|That gave me 19, so Papa Tango query.",
        "-w.|Then we got 32, and that's Kilo Zulu query.",
        "-w.|And finally 99, which is Delta Charlie submit.",
        "-w.|After that noise, well, you already know what happened.",
        "*b.|(I know that noise all too well.)",
        "*w_212429|Alright, let's see if I can see where you went wrong.|bbb|prb|You queried an incorrect number of times.|You mixed up rows and columns in the table.|You had the wrong starting number.",
        "*w,|Ah, I know. You queried an incorrect number of times.",
        "-w,|Edgework, were you even listening? I clearly queried 3 times.",
        "*wX20|Agh! Well that wasn't it.",
        "*w,|Do you think you mixed up the rows and columns in the table?",
        "-w,|...",
        "*w,|...",
        "-w,|That's one of the most ridiculous things I've ever heard.",
        "*bX20|(I didn't mean to insult him.)",
        "*w.|Oh, I see what happened. You had the wrong starting number.",
        "-w.|How exactly did that happen?",
        "*w.|You said you had an RCA port, correct?",
        "-w.|Yeah, I did say that.",
        "*w.|The manual says if you have an RCA port, to double your starting number.",
        "-w.|Oh, okay. Yeah that would explain how I got it wrong. Thanks!",
        "*w!|No problemo."
    };

    public static string[] BlanMorsematics = {
        "Well|3",
        "-w_01|Hello Mr. Edgework.|w|p|Hey there, how's it going?",
        "*w.|Hey there, how's it going?",
        "-w.|Last night a Morsematics strike blew up the bomb.",
        "*b.|(Morsematics, huh? That's one of the most common places to get a strike.)",
        "*w.|Yeah, I'll help you figure out what you did wrong.",
        "-w.|Where do we even begin though?",
        "*b_1207|(That is a good question, where do we begin?)|br|nq|Are you sure you got your inputs correct?|I know you got your inputs wrong.",
        "*w,|I know exactly what happened!",
        "-w,|Do you?",
        "*w,|Yeah, you got your inputs wrong.",
        "-w,|Can you at least let me speak before you make an accusation like that?",
        "*bX06|(I had a feeling that was wrong...)",
        "*w.|Are you sure you got your inputs right? That part is quite tricky.",
        "-w.|Okay, so my final answer was X-ray, which is dash dot dot dash.",
        "-w.|I do very long dashes, medium sized gaps and very small dots. That seems to work for me.",
        "*w.|Alright, you probably got that right. Can you go through the solve itself?",
        "-w.|Of course I can.",
        "-w.|My Morse letters were Oscar, Uniform, and Kilo.",
        "-w.|My Serial Number characters were Papa and Tango.",
        "-w.|I had no indicators so the first rule could not apply.",
        "-w.|Papa is 16, and Tango is 20, added together is 36. Which is 6 squared, so add 4 to A, it's now Tango.",
        "-w.|Adding the largest received letter, Uniform to A, makes A 15, which is Oscar.",
        "-w.|Next rule is subtracting prime letters from A.",
        "-w.|Oscar and Uniform aren't prime, but Kilo is prime. A - 11 = 4, which makes A Delta.",
        "-w.|None of the three letters are squares, obviously, and I had no batteries so the last rule does nothing.",
        "*b.|(No batteries and indicators? That's a strange bomb...)",
        "-w.|B is more than A, so adding A and B, that's 4 + 20, which is 24. X-ray should've been the answer.",
        "*w_342831|Alright, now that I've heard all that...|bbb|rnb|Are you sure 36 is square?|Uniform wasn't the largest letter.|Kilo wasn't the only prime letter.",
        "*w,|...Uniform wasn't the largest letter on the module.",
        "-w,|Do you need to go back to first grade, Edgework? The other letters were Kilo and Oscar.",
        "*wX27|What on Earth was I thinking?!",
        "*w,|...Kilo wasn't the only prime letter on the module.",
        "-w,|That's not right, Oscar is 15 which is divisible by 5. Uniform is 21 which is divisible by 3.",
        "*bX27|(Have I actually gone insane?!)",
        "*w.|...You forgot to keep numbers between 1 and 26.",
        "-w.|Oh?",
        "*w.|You stated earlier that Papa + Tango is 36, but you should've subtracted 26 before checking if it's a square.",
        "-w.|Ah, I see now.",
        "*w!|People make that mistake all the time."
    };

    public static string[] BlanYellowArrows = {
        "West|7",
        "*w.|Woah, is that who I think it is?!",
        "-w_02|Yes, it is who you think it is.|w|n|What do you need?",
        "*w.|Mr. West, how can I help you?",
        "-w_0804|I'll just get straight to the point: I struck on Yellow Arrows. Can you help me?|br|pq|Didn't I just say yes?|I don't help celebrities.",
        "*w,|I'm sorry sir but I don't think I can help you.",
        "-w,|Very well, let me get my business card.",
        "*b,|(Wait, what?!)",
        "*wX08|Lemme read that thing... okay yeah I need to do this don't I, sorry sir!",
        "*w.|Tell me about what happened.",
        "-w.|The display had a Yankee on it, which means to use the rule in the Yankee row.",
        "-w.|\"Press any if up hasn't been pressed yet\", which it has not. So I can press whatever.",
        "-w.|The last digit in the Serial Number is a 5, which means I need to go down 6 rows, I didn't forget to add 1.",
        "-w.|That leads me to the Echo row. \"Press right if lit SIG is present.\" Which there was on the bomb, so right.",
        "*w.|Understood, continue...",
        "-w.|Plus 6 from Echo is Kilo: \"Down if 9 is an odd number.\" Is 9 odd, Edgework?",
        "*w.|...yes.",
        "-w.|So that means the next press is down. After that is the Quebec rule.",
        "-w.|\"Down if previous input was right...\" Which is not true, \"...otherwise left.\" So next is left.",
        "-w.|And finally the Whiskey rule. \"Right if no port plates are present.\" There were port plates on the bomb.",
        "-w.|\"Otherwise left.\" Which means that down, right, down, left, left is an acceptable sequence. But it wasn't.",
        "*w_212528|Alright, I think I see what you did.|bbb|rkb|You're not supposed to add 1 to 5.|You are incapible of adding 6 to letters.|You don't use the starting row's rule.",
        "*w,|What gave you the idea to add 1 to 5 like that?",
        "-w,|\"Then, take the last digit of the Serial Number plus one, and move down that many rows.\"",
        "-w,|That did say \"plus one\", did it not?",
        "*wX20|Argh! It did!",
        "*w,|I believe you messed up one of the plus 6s.",
        "-w,|Then I'll just say letters in groups of 6. Yankee... ZABCD.. Echo, FGHIJ.. Kilo, LMNOP.. Quebec, RSTUV.. Whiskey. ",
        "*bX20|(How is Kanye smarter than me???)",
        "*w.|Oh, I see. You used the rule in the starting row when you weren't supposed to.",
        "-w.|Wait, what?",
        "*w.|It says to move down however many rows before you apply any rules.",
        "-w.|Ah okay that makes sense, I'll likely come back here for any other inquiries regarding modules.",
        "*b!|(Sounding so professional... I should try that.)"
    };

    public static string[] BlanLEDEncryption = {
        "Wiohgi|8",
        "*b.|(Hmmm what do I do-- wait a minute, is that banging on my door?)",
        "*w.|COME ON IN!!!",
        "-w.|Hello sir, we're in an emergency.",
        "*w.|An emergency?",
        "-w.|We're mid-bomb and LED Encryption has no correct answer.",
        "*w_06|Oh, okay! Let's not waste any time then!|w|q|Give me the read.",
        "*w.|What is the read?",
        "-w.|First stage color is red. Oscar, Tango, Zulu and Uniform are your letters.",
        "-w.|15x2=30, minus 26 is 4, not 21. 20x2=40, turns into 14 which isn't 26...",
        "-w_1013|...26x2=52, minus 26 is definitely not 20. 21x2=42, minus 26 is 16 which isn't 15! Nothing works!|bb|nb|Press Oscar.|Press Uniform.",
        "*w,|Okay, press Oscar.",
        "-w,|...that gave us a strike!",
        "*wX09|Crap!",
        "*w.|Press Uniform.",
        "-w_211518|Okay, that worked. Can you tell me what I did wrong so I can do the rest?|bbb|kpr|Numbers are 0-indexed.|You multiplied by the wrong number.|You're not supposed to multiply.",
        "*w,|You weren't supposed to multiply by 2.",
        "-w,|What do you mean it says 2 under red in the table...",
        "*wX14|Whyyyy...",
        "*w,|You don't multiply in this module.",
        "-w,|That is just not right, I think I might've banged on the wrong person's door.",
        "*wX14|I'm sorryyyyy!",
        "*w.|Alpha is 0 on this module, not 1.",
        "-w.|Wait, really?",
        "*w.|Yes, and Bravo's 1, Charlie's 2, you get the idea.",
        "-w.|Okay it says we completed the bomb in 17 minutes and 41 seconds.",
        "*b!|(Wait a minute, does that mean the bomb was in Zen mode?)"
    };

    public static string[] JamieFMN = {
        "Blimp|4",
		"-w.|Huh?",
		"-w.|Why was that wrong?",
		"-w.|Uh, Mr Edgework? Can you take a look at this?",
		"+b_04|(This is the fourth time Blimp's asked me today, what now?)|w|p|What's the problem?",
		"-w.|Ok, so I was learning Forget Me Not and I pressed the first 4 digits correctly.",
		"-w.|Then, I got the 5th stage wrong.",
		"+w.|No point just telling me that it was wrong, what did you do for that stage?",
		"-w.|...I was literally about to tell you.",
		"-w.|I submitted 4858 so far, and the displayed digit was a 5 for that stage.",
		"-w.|There are no zeros in the previous two and there aren't two even numbers, so I add the previous two digits together.",
		"-w.|After that you take the least significant digit and add the displayed digit, which should give me 8, but it wanted 6.",
		"+w_121619|Hmmm, yeah I see what happened.|rww|qbn|The module is bugged.|You need to subtract the displayed digit.|You need to take the most significant digit.",
		"-w,|Wh- It's bugged?",
		"-w,|You're telling me this mod that's been out for 4 years is bugged?",
		"-w,|4 YEARS?",
		"+bX11|(Oh hold on let me think about this again, there's no way that it's bugged after all this time.)",
		"+w,|Yeah, I see, you are supposed to subtract the displayed digit instead of add.",
		"-w,|Ok, so that means I need to do 8 + 5 - 5, which gives me, What? That still doesn't give me the right answer?",
		"+bX11|(Coming to think of that, I'm pretty sure I remembered the rules wrong, I may need to get more sleep.)",
		"+w.|Yeah, I see, you need to take the most significant digit instead of the least.",
		"-w.|Wait, what? What does that mean?",
		"+w.|Most significant just means the first digit, so the sum of 8 + 5 is 13, and the most significant digit is 1.",
		"-w.|So I add this 1 to the 5, which gives me- Ohhhhh!",
		"+b!|(This rule used to always trip me up, but I'm glad I remembered it properly this time.)"
    };
	
/*	public static string[] MehCornflowerButton = {
		"Craft|5",
		"-w_0401|Hey there, Mr. Edgework.|bb|pq|Hey.|GET OUT OF MY FACE, JERK",
		"+w,|GET OUT OF MY FACE, JERK",
		"-w,|What in the world is wrong with you..?",
		"+bX00|(I'm losing myself...)",
		"+w.|Hey.",
		"-w_06|So I've been learning a bunch of new mods lately...and there's this one module I was very confused on.|w|r|What mod is it?",
		"+w.|What's this module that made you confused?",
		"-w.|Shameful to say...The Cornflower Button.",
		"+b.|(Ah, one of the button modules. The Cornflower button shouldn't be that big of a deal if you had watched the tutorial...)",
		"+w.|Which part are you confused on exactly?",
		"-w.|Well, okay. It was the switching highlighted pivots part, about the hovering selectable thingy.",
		"-w.|I ran a bomb, and just as the manual suggested, I hovered the selectable pointed by the arrow and deselected it, and guess what?",
		"-w.|The highlighted arrows didn't change at all!",
		"+b_142017|(Hm...weird indeed, but I don't think I have enough information to deduce what's going on.)|bbb|kqb|Could you give me the edgework of the bomb?|What modules are there in the bomb?|Could you give me the colours in the display?",
		"+w,|What's the edgework of the bomb?",
		"-w,|Why do you need the edgework? The module doesn't even need edgework, if I understood correctly.",
		"+bX11|(Ah yeah...)",
		"+w,|What are the colours on the bottom display of the button?",
		"-w,|Uh...Mr. Edgework, we're talking about Cornflower Button here.",
		"+bX11|(Why did my mind drift off to The Yellow Button instead?)",
		"+w.|What modules do you have on the bomb?",
		"-w.|Hold on, let me grab the log.",
		"-w.|Hmm...besides The Cornflower button, I also have Painting, Simon Subdivides, Standard Crazy Talk, Antistress, Deaf Alley...",
		"-w.|...Art Appreciation, and Quizbowl on the bomb.",
		"+w.|Do you still remember where is the arrow pointing to?",
		"-w.|I think it points to one of Subdivides' buttons, but I tried it on the button and nothing happened.",
		"-w.|Come to think of it, the arrow itself is sort of moving in its own though...",
		"+b_283237|(Wait, does that mean...)|bbb|bnr|You should press the selected button.|You did not deselect correctly.|The arrow isn't pointing to the button.",
		"+w,|Yeah, you definitely should press the pointed button instead.",
		"-w,|...Mr. Edgework, not to be rude, but have you read the manual? It clearly states to only highlight the selectable, not press it.",
		"+b,|(Ah, and pressing the button would most probably incur a strike on the bomb too, we ain't dealing with Button Messer here.)",
		"+bX27|(Oh crap, I feel so embarrassed...)",
		"+w,|Are you sure you deselected the module correctly?",
		"-w,|...What are you talking about?",
		"+w,|Well, you know, highlight the selectable, and deselect it.",
		"-w,|I'm pretty sure I did that correctly, I did it a million times and it still won't work!",
		"+bX27|(Oops...)",
		"+w.|Before we continue on, can I confirm Quizbowl's location on the bomb?",
		"-w.|Let's see...it's located in the top left, directly above the timer.",
		"+w.|And let me guess, is the Cornflower Button located in the face directed opposite to where the Timer is?",
		"-w.|How did you know that?",
		"+w.|Then that explains it. The Cornflower button isn't pointing to Subdivides' button.",
		"+w.|In fact, I doubt that it points to anything on the bomb at all. All others but Quizbowl are modules ignored by Cornflower Button.",
		"-w.|Ah, so which means...",
		"+w.|That's right, the module is actually pointing to the alarm clock instead.",
		"-w.|Makes sense! Thank you Mr. Edgework!",
		"+w!|Anytime, man."
	}; */
	
	public static string[] AxodeauBombDiffusal = {
		"Axodeau|5",
		"-w.|Hey, Edgework!",
		"+w.|Oh, hello there.",
		"-w.|I struck on Bomb Diffusal earlier, but I have no idea what I did wrong...",
		"+w_0417|Okay...|br|pn|Tell me the read|Let me telepathically work it out.",
		"+w.|What was the serial number and license number?",
		"-w.|Serial was AV5QL7, license number was 4L41TY.",
		"+w.|Right, and what numbers did you get out of the table?",
		"-w.|194935",
		"+w.|Yep, I agree with that.",
		"-w.|So, the destination is Space, right? Since the 9s cancel out, leaving the 5 at the end to be the largest.",
		"+w.|Mhmm...",
		"-w.|Taking the first 2 numbers modulo 5 is 14, which is Io.",
		"+w_191322|Okay, I think I've found the problem|bbb|pbn|You use the 2nd and 3rd digits|You're meant to reverse the license number|14 isn't Io",
		"+w.|\"If the delivery destination is space, reverse the delivery number for the next step...\"",
		"-w.|Ooooh. Setting it to Jupiter (03)... Yep, module solved now. Thankfully the rest was right though.",
		"+w.|Alright, good job on the rest of it.",
		"+b!|Always read through a manual to spot any fine prints. They could be what is causing you to strike.",
		"-w,|Are you kidding me? I could literally just tell you the read.",
		"+wX04|Oh, right, yeah, good point.",
		"+w,|You have to use the 2nd and 3rd digits of the resulting number.",
		"-w,|Uhhhh, no you don't, it says first and second.",
		"+wX12|Oh, yes it does, sorry, my bad.",
		"+w,|14 isn't Io, it's Europa.",
		"-w,|... Nope, 14 is Io for sure.",
		"+wX12|Oh, forgive me for that, Io is most definitely 14, woops..."
	};
	
	public static string[] AxodeauGarnetThief = {
		"Kaylib|2",
		"-w.|Edgework... I need some help.",
		"+w.|Oh, hello there, what module do you need help on?",
		"-w.|The Garnet Thief.",
		"+w.|Ok. Who do you have?",
		"-w.|Kyungran (M), Jinho (M), Junghyun (P), Yeonseung (C), Junseok (C), Yoonsun (P), and Sangmin (B).",
		"+w.|... Alright, noted all of that down. What condition did you have in the table?",
		"-w.|No word of a lie, the first one. My serial number was AA1PL1. This is a 1 module bomb by the way, if that helps.",
		"+w.|Ok, that checks out. Also, yeah, that will be useful.",
		"-w.|Kyungran, Junseok and Sangmin were lying. They are now Cartel, Mafia and Police respectively.",
		"+w.|Mmhmm...",
		"-w.|So, there are now 2 cartel, 2 mafia, and 3 police, right?",
		"+w.|Mhm.",
		"-w.|Meaning Police get more than any other faction, but that was wrong.",
		"+w_262914|Aha, I've worked out what you did wrong.|bbb|pbn|You've got the numbers wrong.|Someone else was also lying.|You're picking a faction as well.",
		"+w.|You do remember you're picking a faction as well, and you count as an extra member of that faction?",
		"-w.|... OOOOOOH, that's what I've forgotten.",
		"-w.|...",
		"-w.|Wait, they're all the same, what do I pick? Mafia and Cartel have the same lowest amount?!",
		"+w_323519|Uhhh...|bbb|pbn|Mafia|Cartel|Beggar",
		"+w.|Neither, it's beggar.",
		"-w.|Why?",
		"+w.|Zero claims, which is less than two claims.",
		"-w.|Oh, I must've thought it didn't count if it wasn't there. Sorry about that.",
		"-w.|Yep, solved now, thanks for the assistance.",
		"+w.|No problem.",
		"+b!|(I really like Garnet Thief, it's quite an interesting puzzle.)",
		"+w,|Are you sure you've counted them correctly?",
		"-w,|Yep. 2, 2 and 3 still.",
		"+wX13|Damn, right, back to the drawing board...",
		"+w,|Someone else was lying.",
		"-w,|Who?",
		"+wX13|... I don't know. Nevermind...",
		"+w,|Mafia?",
		"-w,|Nope, strike.",
		"+wX18|Hmmmm...",
		"+w,|Cartel?",
		"-w,|Strike, not right.",
		"+wX18|Hold on..."
	};
	
	public static string[] AxodeauBafflingBox = {
		"Baffed|1",
		"+w.|*whistling to themselves*",
		"+w.|Huh...",
		"-w.|Hello, Edgework, I heard you can help me if I strike I don't know how, am I correct?",
		"+w.|Yep, what module was it?",
		"-w.|Baffling Box, do you know that one?",
		"+w_0618|Um...|br|pq|Yeah|I don't know what you're talking about.",
		"+w.|Yep, I think so. What indicators do you have?",
		"-w.|3 lits and 3 unlits, so I used the X axis to read it.",
		"+w.|First, tell me what you saw from straight on, from the left and from the top of the module, in that order.",
		"-w.|Red Cube, Orange Sphere, Green Cylinder.",
		"+w.|Ok, so what was the parity of the last SN digit?",
		"-w.|Even, so the intersection of the table was Z, X, Y, which corresponds to Red, Orange, Green, which is 0...",
		"+w_132124|Ok, wait there, I think I know what you did.|bbb|pbn|You mixed up your axes|You read the colours wrong|R, O, G is not 0",
		"+w.|Ah, yep, classic mistake for this. Despite top sounding like it is referring to looking from the top of the module...",
		"+w.|It is actually the straight on view that it is referring to, like in Hypercube, if you've done that one.",
		"-w.|Ah, right, so it would actually be Green, Orange, Red... waiting for :5X... Yep, solved now. Thanks for that.",
		"+w.|Glad to be of assistance!",
		"+b!|To be fair, I was confused by that when I first did that module.",
		"-w,|Oh, well, you can't help me then...",
		"+b,|Wait, I do know that module, I almost know all of them, what was I talking about...",
		"+bX00|*rewinds tape*",
		"+w,|You read the colours wrong then.",
		"-w,|Uhhh, no, I definitely got the colours right. Wait, how would you know if I read them wrong if you can't see the bomb?",
		"+wX12|Good point, I don't know...",
		"+w,|Are you sure ROG is 0, yeah?",
		"-w,|Yep, most definitely.",
		"+wX12|Woops, yes, it most definitely is. Let me think again..."
	};
	
	public static string[] AxodeauRebootingMOS = {
		"Derek|8",
		"-w.|Edgework! Edgework! Need help!",
		"+w.|Oh, uh, hello. What module?",
		"-w.|Do you know Rebooting M-OS?",
		"+w.|Yep, what have you already done?",
		"-w.|Well, I got the status light press right, but the final answer wrong.",
		"-w.|I've already double checked A, B and C, and am 110% sure on those.",
		"+w.|Those being...",
		"-w.|Oh yeah, A = 104, B = 658, C = 50",
		"+w.|Okay, just to confirm, what base 3 number did you receive for value C?",
		"-w.|121",
		"+w.|Ok. What was your final result after altering it, and what equation did you use?",
		"-w.|188, after adding 100 to  -612 8 times, and, since the last digit of the serial was 5, I used equation 5, 3C - (A+B).",
		"+w_171320|Ok, something has definitely gone wrong here...|bbb|pbn|121 doesn't refer to 50|You make any negative value positive first|The equation doesn't equal -612",
		"+w.|Aha, there it is. You take the absolute value of the number first, before any modulo or adding.",
		"-w.|Ah, yes, missed reading that bit. Just saw 'less than 100' and went forward without question.",
		"+w.|Don't worry, easy mistake to make.",
		"+b!|(Why does M-OS have such a complicated reboot method anyway?)",
		"+w,|Is 121 definitely 50 in the table?",
		"-w,|Yep, a thousand percent yes.",
		"+wX12|Oh, ignore me, it is, my bad...",
		"+w,|It doesn't equal -612.",
		"-w,|3(50) = 150, 104+658 = 762, 150-762 = -612. What are you talking about?",
		"+wX12|Nevermind, yes it does, hmmm, what else could've happened?"
	};
	
	public static string[] UsernameChess = {
		"Noma|6",
		"-w_01|Greetings Mr. Edgework, do you have a moment?|w|p|What's up?",
		"+w.|Indeed I do, what seems to be the issue?",
		"-w.|I was busy practicing for a challenge bomb, and I can't seem to find out where I went wrong on Chess.",
		"+b_0604|(Practicing Chess for a challenge bomb? Strange...)|br|pn|What's the read?|Which challenge bomb?",
		"-w.|Ah, I'm doing Brain Power again. Why do you ask?",
		"+w_06|Oh, just curious that's all.|w|p|What's the read?",
		"-w.|D6, A5, C1, F6, E3, and E4 are my coordinates.",
		"-w.|Serial Number was odd.",
		"-w_0910|After putting the pieces on their respective spots, I see that there are no uncovered spots by the chess pieces.|ww|rb|What about Rule Seed?|That's all I need.",
		"-w.|My apologies, almost forgot. Standard Rule Seed 1.",
		"+w.|I see, thank you.",
		"+b_1220|(No uncovered spots? Hmmm...)|br|kq|Can you provide more information?|I see the problem already.",
		"-w.|Certainly. We both know that Position #4 is a Rook. So Rook takes F6.",
		"-w_1417|E3 is a black square. Meaning a Rook takes E3, and a Bishop takes D6, Positions #5 and #2 respectively.|br|bp|One of your pieces so far are incorrect.|Wait and see.",
		"-w,|Uhh... You sure there Mr. Edgework? Those three spots are usually the ones everybody never gets wrong.",
		"+bX16|(Everyone except me I guess...)",
		"-w.|Anyways, where was I? Oh yes.",
		"-w.|The serial number is odd, so A5 - Position #2 is taken by a Rook.",
		"-w.|Finally, since we have three Rooks, Position #3 is taken by a King, and #6 is taken by a Queen.",
		"-w_242927|And this is where I come to you. Being stumped on where could this uncovered square lie, I look forward to hearing your reasoning.|bbb|ppp|Submit D2.|Submit B6.|Submit B4.",
		"-w.|Oh do you?! What's the solution then?",
		"+b_2223|(Do I really know what the answer is? I'm confident I do already, but should I ask for more information just in case?)|wr|pp|Can you provide edgework?|I have everything I need.",
		"-w.|Sure, Odd Serial and Rule Seed 1. Let's see that intuition at work!",
		"+w_242927|The answer here is to...|bbb|bnr|Submit D2.|Submit B6.|Submit B4.",
		"-w,|D2? Isn't that spot claimed by the King in C1?",
		"+b,|(Whoops, I didn't see that.)",
		"-wX23|So much for that Edgework Intuition I was expecting...",
		"-w,|B4? Sir, that's covered by a Bishop and Queen!",
		"+bX23|(He's absolutely right, I should be more careful next time.)",
		"-w.|B6? But the Rook at F6 captures it?",
		"+w.|Although technically true, you missed one crucial detail, and I happen to know why.",
		"-w.|What...? What detail?",
		"+w.|Do you happen to use the interactive of the Chess manual?",
		"-w.|Why yes. In fact I only used the interactive from when I first learned it.",
		"+b.|(Exactly what I was hoping to hear.)",
		"+w.|You have missed a very important detail all because you have only used an interactive manual.",
		"-w_3937|An important detail missed? What is this detail then?|bb|kq|The chess pieces can block each other's movements.|The chess pieces are colorless.",
		"-w,|What does the color of the pieces have to do with anything?",
		"+wX36|I don't know either!",
		"+w.|By having the pieces block each other, the Rook at F6 gets blocked by the bishop at D6.",
		"+w.|Meaning, the only uncovered square is in fact B6.",
		"-w.|And that's a solve! I'm a little embarrassed that that was the reason why I couldn't solve this Chess. Many, many thanks!",
		"+w!|Always a pleasure."
	};
	
/*	public static string[] MehBrainf = {
		"Ded|1",
		"+b_01|(What's the guy doing, laying on the floor like that?)|w|p|Uh...are you okay?",
		"+w.|You okay there?",
		"-w.|...",
		"-w.|Mr. Edgework.",
		"+w.|Yes?",
		"-w.|Mr. Edgework!",
		"+w.|Uh, yeah, that's me.",
		"-w.|MR. EDGEWOOOOOOOOOOOOOORK!!!!!",
		"+b_1209|(Did he hit his head or something?)|br|pb|Are you okay?|Walk away.",
		"+b,|(I'd better just leave him be...)",
		"+b,|(...)",
		"+bX12|(Yeah, nope. Can't just leave a guy like that alone.)",
		"+w.|What's the matter? Are you okay?",
		"-w.|MR. EDGEWORK! PLEASE! I ALMOST SOLVED THAT NASTY CENTURION! BUT THEN I GOT THE WRONG ANSWER FOR THE FINAL BOSS AND- AND-",
		"+b.|(...He started crying.)",
		"-w.|Y-YOU GOTTA HELP ME MAN!!!!!!! I WASTED A R-REALLY REALLY G-GOOD SOLVE ON SOMETHING I DON'T UNDERSTAND AT ALL??????",
		"-w_1917|PLEEEEEEEEEASE!!! I'M BEGGING YOU!!!!!!!|br|bn|I'll help you out.|Get Lost.",
		"+w,|I don't have time for your gibberish. Get lost.",
		"-wX19|BUT MR. EDGEWOOOOOOOOOOOOOOOOOOOOOOOOOOORK!!!",
		"+w.|Alright, just firstly, calm down. I'll help you in discovering your mistake. Here, take a tissue and wipe your tears off.",
		"-w.|...",
		"+b.|(Guess he calmed down a bit...that's the first step done.)",
		"+w.|Alright, now tell me. What is the boss that you had struck on?",
		"-w.|B-b-brainf---",
		"+b.|(Oh, but that's a fairly easy boss. How did he managed to screw up?)",
		"+w.|Okay, so BrainF is it? Give me your workings.",
		"-w.|S-so in the first f-few stages I have p-plus, minus, t-two right symbols, another m-minus, and a left symbol...",
		"-w.|...w-which should r-result in the p-pointer getting in t-the s-slot 1, and to the right we have v-value o-one...",
		"-w.|...t-then th-the first loop h-happened, wh-which only c-contains one r-right symbol a-and t-two plus symbols...",
		"-w.|...a-as I have f-four batteries, I should l-loop it f-four plus o-one times, w-which is five, giving me f-five twos in a r-row...",
		"-w.|...th-then a minus s-symbol, then another m-more complex l-loop w-with t-three right symbols, two p-pluses, a left s-symbol...",
		"-w.|...three m-minuses, a-and another t-two right symbols...s-so I-I looped t-the same way as w-well, giving me 0, 0, 3, 2, 2, 2, ...",
		"-w.|1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, ...",
		"+w.|Alright, you can stop there. Pretty sure I figured it out where you get wrong.",
		"-w_354047|Wh-wha? B-but where?|bbb|rqq|Before the first loop.|In the first loop.|In the second loop.",
		"+w,|You did something wrong in the code before the first loop.",
		"-w,|Wh-wha? I s-still d-don't understand...",
		"+w,|Your minus code. How could you add one instead of subtracting from the slot?",
		"-w,|Th-the zero case? Wh-where the s-slot is z-z-zero???",
		"+bX34|(Oh yeah...)",
		"+w,|There's something wrong when you execute the first loop.",
		"-w,|B-but wh-where?",
		"+w,|Well, five twos in a row seem odd. Why is that?",
		"-w,|Be-because it's the r-result of the c-code??",
		"+w,|Obviously, when you did something wrong. You see-",
		"-w,|Mr. Edgework, there are only three symbols in the loop. Are you dumb? That's just plain ridiculous.",
		"+bX34|(Ack...you're one to talk...how humiliating...)",
		"+w.|You make a mistake while executing the second loop.",
		"-w.|B-but wh-where?",
		"+w.|The number of loops. You looped too many times.",
		"-w.|I-I did n-not??? It's f-four batteries plus o-one l-loops, no?",
		"+w.|It's true that you can loop five times, but keep in mind this is the maximum number you can only loop.",
		"+w.|In fact, you should only execute the loop once, as at the end of the loop the pointer points to zero.",
		"-w.|...I-I g-guess.",
		"+w.|C'mon, everybody makes mistakes, there's no need to cry over such a small error. Just keep that in mind, and you should be okay.",
		"-w!|...Thank you."
	};*/
	
	public static string[] AxodeauInterpunct = {
		"Q|9",
		"+w.|Man, I really haven't had a lot of people come to me for he...",
		"-w.|Are you busy Edgework?",
		"+b.|(Spoke too soon...)",
		"+w.|No, what do you need help with?",
		"-w.|I'm normally consistent with Interpunct, but I just struck and don't know why.",
		"+w_0616|Umm...|br|pp|I can help with that|You struck on Interpunct?!",
		"+w.|Sure, I can help with that. What symbols were you given?",
		"-w.|Speech Marks, with given symbols open square bracket, vertical bar and what I would call a fast forward symbol.",
		"+w.|And what did you press?",
		"-w.|The fast forward, but it said I was wrong.",
		"+w_191122|Ummmm... Yes, I've got it. I know the mistake here...|bbb|pbn|The table doesn't wrap around|You've mixed up 2 symbols|You choose the one that isn't adjacent",
		"+w.|Did you notice there are two different speech marks in the table?",
		"-w.|Oh, my, there are 2 different speech marks, and yes, the other set look more like the ones I had on the module.",
		"+w.|Ok, that sorts it out.",
		"-w.|Thanks Edgework.",
		"+w!|No problem.",
		"-w,|Alright, there's no need to be like that Edgework! I know it's an easier module, but bear with me here!",
		"+b,|(I don't know what came over me there, I'm not normally like that.)",
		"+wX06|Sorry, bit of an overreaction from me there. I can only apologise...",
		"+w,|The table doesn't wrap around.",
		"-w,|Uhhh, that doesn't matter in this scenario though. Fast forward is quite literally adjacent to the speech marks I'm on about.",
		"+wX10|Woops, of course that doesn't matter here...",
		"+w,|You choose the one that isn't adjacent to the screen.",
		"-w,|No, I've done this enough times to know that you have to pick the one that is adjacent.",
		"+wX10|Nevermind, re-read it and yes, you do pick one that is adjacent. Let me have another look..."
	};
	
	public static string[] UsernameCoordination = {
		"Blade|3",
		"-w.|Oh dear... there go all my papers.",
		"+w.|Let me get those for you.",
		"-w.|Ah, Mr. Edgework, it's an honor to be in your presence.",
		"+b.|(It's always a good thing to know that my reputation has got me far around these parts.)",
		"+w.|Are these all paper manuals?",
		"-w.|You bet! I've been using these since I've first gotten into the EFM game!",
		"+b.|(Isn't it faster to use the repository?)",
		"-w_08|Well, anyways that's beside the point. I'm still in my own confusion right now.|w|p|What seems to be the issue?",
		"-w_1209|I was trying to learn new mods and got an Assorted Arrangement strike.|br|pb|Let's see if I could help.|Do you have a logfile?",
		"-w.|What's a logfile?",
		"+b.|(With the paper manuals and the lack of knowledge of a logfile. He appears to be a little too old school.)",
		"+b.|(I think I don't have a choice but to manually help him.)",
		"+w.|What were your four items?",
		"-w.|Yes, here you go.",
		"+b.|(He handed me a paper. It's filled with notes and scribbles.)",
		"+b.|(Come on, where is this read? Oh, there it is.)",
		"+w.|\"Cup, Trumpet, Banana... Sus?\"",
		"-w.|lol",
		"+w.|...",
		"-w.|...",
		"+w.|...",
		"-w.|...",
		"+b_23|(He's one of THOSE people... let's help him as quickly as possible to avoid more of these jokes.)|b|p|Do you remember what you pressed?",
		"-w.|That I do remember. I pressed the Top left Button 12 times, and the Bottom Right button 7 times.",
		"-w.|I then submitted the module, to which I was presented with a strike.",
		"-w.|If you have any doubts, I wrote it down here.",
		"+b.|(He handed me another paper.)",
		"+b.|(Upon further inspection it was the Assorted Arrangement manual, with writing that does match his presses.)",
		"+w.|I see, it's all coming together.",
		"-w.|What do you mean?",
		"+b.|(Looking at this manual there doesn't seem to be any inconsistencies from what I remember of the digital variant.)",
		"+b.|(However, something doesn't sit right. Especially since this person is a paper manual user.)",
		"+b_393336|(The issue is clearly because...)|bbb|pbn|You pressed the wrong amount of times.|You pressed the wrong buttons.|You noted the wrong symbol.",
		"-w,|I don't think I did, Mr. Edgework.",
		"-w,|It clearly says that Top Left cycles the letter, Bottom Right cycles the number, and Top Right submits.",
		"+bX32|(Indeed it does...)",
		"-w,|You think that I misread a symbol?",
		"+w,|I mean... I'm not saying that you did mistake a symbol...",
		"+bX32|(On second thought, I am saying that they mistook a symbol...)",
		"-w.|Wrong amount of times? How come?",
		"+w.|Although this manual does explain it too, the updated repository manual states a much more explicit A1.",
		"+w.|Which is in between the first 2x2 of items, not the top left corner.",
		"+w.|You needed to press each button one less than what you pressed.",
		"-w!|It all makes sense now! I should probably update my manuals sometime today. Thanks for the help!"
	};

	public static string[] AxodeauPasswordGenerator = {
		"Sebastian|6",
		"-w.|Come on... what am I doing wrong?",
		"+b.|(Hmmm, someone seems confused...)",
		"-w.|Where's Edgework when you need them?",
		"+w.|Uhhh, I'm right here.",
		"-w.|Oh, hi Edgework, I need help on Password Generator.",
		"+w_0619|Hmmm...|br|pn|I can help with that.|You're on your own.",
		"+w.|Sure, what's your edgework?",
		"-w.|3/2, Lit SIG, unlit TRN, plate DVI PS2 RCA, serial TL9HH0",
		"+w.|Noted. So what do you have currently?",
		"-w.|First letter is T, 20 mod 6 + 1 = 3 which is C?",
		"+w.|Mhmm.",
		"-w.|Then for other edgework, it is 4,3,4, after adding 1, which is reversed, but that doesn't change it, so DCD.",
		"-w.|No Question Mark, but yes to Astrology, so *. I also have Diophantine Eq., UltraStores and M-Seq, but those are ignored.",
		"-w.|3 solved,  7 unsolved on a 10 mod bomb, and 9 mins left gives 189, last digit 0, so nothing happens.",
		"-w.|Mod 100 is 89. But CDCD*89 was wrong...",
		"+w_212416|Aha, I know what happened...|bbb|bnp|You moduloed wrong.|The symbol goes at the end.|Another module mentioned is relevant.",
		"+w.|Remind me what other modules you had again, minus Question Mark and Astrology.",
		"-w.|Diophantine, M-Seq, UltraSt... OH, the special case for UltraStores, which is *DEAD*. Sorry to bother you, solved now.",
		"+w!|No worries, have a nice day.",
		"-w,|Huh? No, I thought that was your job, no?",
		"+wX06|Woops, sorry, dunno why I said that, of course I can help",
		"+w,|Are you sure you moduloed right?",
		"-w,|Uhhh, yeah, 189 mod 100 is equivalent to 189-100 = 89, and 20 mod 6 is 2.",
		"+wX15|Oh, right, yeah, ignore me then.",
		"+w,|The symbol goes at the end if I recall correctly.",
		"-w,|Well, I'm sorry to tell you it doesn't.",
		"+wX15|Oops, nevermind, I misremembered, hmmm..."
	};

	public static string[] SamfundevCheepCheckout = {
		"Em|4",
		"-w.|WHAT!",
		"-w.|Wasn't I supposed to slap them?!",
		"+w.|Slap them?",
		"+w.|What seems to be going on here?",
		"-w.|Oh, it's Edgework.",
		"-w.|Sorry, I'm confused what I did wrong on this Cheap Checkout.",
		"-w.|They didn't give me enough change.",
		"-w.|So I asked them for more change...",
		"+w.|Oh so you, uh, \"slapped\" them?",
		"-w.|Yeah! But I got a strike.",
		"+w_1115|So wait...|rw|qk|Why did you slap them?|What's on the module?",
		"-w,|I didn't literally slap them, Edgework!",
		"-w,|I just asked them for more change.",
		"+bX14|(Whoops! He already went over this.)",
		"+w.|Right, sorry.",
		"-w.|They bought a Lollipop, some Gum, some Spaghetti, Pasta Sauce, 1.5 pounds of Oranges, and half a pound of Potatoes.",
		"-w.|Today is Sunday so I applied the sale to the Spaghetti and Pasta Sauce.",
		"-w.|Ran the numbers through my calculator, but they still didn't pay enough.",
		"+w_271922|Ah, I know what's wrong here.|www|nbr|You applied the sale to the wrong items.|You did the math wrong in your head.|You got the categories of the items wrong.",
		"-w,|In my head? I said I used a calculator.",
		"+b,|(Gotta pay more attention, he did say that.)",
		"+wX18|My bad, let me take another crack at this.",
		"-w,|The categories, what do they have to do with this?",
		"+w,|Lollipops a sweet, so they are 35% off.",
		"-w,|That's the rule for Saturday, it's Sunday!",
		"+b,|(Gah, I got the two mixed up!)",
		"+wX18|Heh, just testing you. What I meant to say was...",
		"-w.|The wrong items? Which one was wrong?",
		"+w_332931|You messed up the...|www|ppp|Lollipop|Spaghetti|Pasta Sauce",
		"-w,|Spaghetti starts with an S. Pretty sure I got that one right.",
		"+bX28|(Jeez, how did I miss that one?)",
		"-w,|Pasta Sauce has an S in \"Sauce\".",
		"+bX28|(Right, it's not just items that start with an S.)",
		"+w.|It's Lollipops, not just a single Lollipop. So it has an S in it.",
		"+w.|Which brings the final price up, meaning you have one slapped customer to apologize to.",
		"-w.|Oh gosh, I've really messed up! I need to go talk to them.",
		"-w!|Thanks for that Edgework!"
	};

	public static string[] BlanResistors = {
		"Latkovich|10",
		"-w.|Hello there.",
		"+w.|Hi how can I--",
		"+w.|ARE YOU NICK LATKOVICH???",
		"-w.|Yes.",
		"-w.|I have an odd request for you.",
		"+w.|How so?",
		"-w.|This is more of an electronics question than a KTANE one...",
		"-w.|...but I am aware of the existence of a Resistors module.",
		"+w.|I think I know resistors quite well.",
		"-w_0610|Good.|rw|pn|Wait a second, what am I dealing with again?|So... what's your question?",
		"-w.|I have an LED...",
		"+w.|Uh huh.",
		"-w.|...and a resistor.",
		"+w.|Seems legit.",
		"-w.|The LED didn't turn on though.",
		"+w_1617|Hmmm...|rw|qb|I give up.|What's the colors on the resistor?",
		"-wX15|Oh okay.",
		"-w.|Blue, gap, Violet, White, White.",
		"+w.|Oh I see the problem now.",
		"-w.|Really?",
		"+w_212925|Of course!|www|rkq|The gap means the resistor is broken!|You're using too much power!|You're not using enough power!",
		"-w,|You're joking right?",
		"+w,|What do you mean?",
		"-w,|There's no way the resistor's broken.",
		"+wX20|...oh.",
		"-w,|Uh, Edgework?",
		"+w,|Yes?",
		"-w,|That cannot be the case. If it wasn't enough I'd imagine there would be some light.",
		"+wX20|You have a point, shoot.",
		"+w.|Take a look at the color chart.",
		"-w.|Okay, what does this mean?",
		"+w.|It tells you how many ohms the resistor can handle.",
		"-w.|I see.",
		"+w.|White, White, Violet (reading from right to left, so the gap is on the right) then Blue means the resistor can handle 997...",
		"-w.|997?",
		"+w.|...million ohms. Pretty overkill if you ask me.",
		"-w.|Ah, I see. Thank you so much.",
		"-w.|I guess it's time to buy some new resistors with this chart in mind.",
		"+w.|And a new LED too, there's no way that'll work.",
		"+b!|(Or at least I assume so, I'm not an electronics expert...)"
	};
}
