public class logicChessData
{
    public static string[] Case0 = {
        "Rene|9",
        "+b.|(She seems annoyed at herself.)",
        "-w_02|I can't believe I almost blew up during that bomb.|w|p|What happened exactly?",
        "+w.|Can you tell me what happened during the bomb that's making you so annoyed?",
        "-w.|Annoyed? What do you mean annoyed?! I did manage to solo the bomb y'know!",
        "+b_0508|(She's known for being good at soloing however making a mistake gets on her nerves.)|br|bp|I don't believe you soloed the bomb!|Wait and see.",
        "+w,|I'm sorry but I refuse to believe that soloing that challenge bomb is possible.",
        "-w,|Do you know who I am!? I've defused a bunch of bombs, strike free!",
        "+wX08|Nnnghhh!",
        "-w.|The one thing I struck on was Mssngv Wls. The first module was obviously Painting, which rules out A and I.",
        "-w.|The second module must've been Meteor, which rules out E and O. That means the missing vowel is U.",
        "-w.|The missing hieroglyph was Lion, and therefore Two Reeds must've been right, but it wasn't.",
        "-w.|After that I just started guessing as there was only one other module left.",
        "+w.|I believe I understand your situation now, thank you for sharing that.",
        "-w_142017|Wait... did I really say all that out loud? I thought all of that was in my head.|bbb|bnr|Are you sure that there was 'Painting'?|Are you sure that there was 'Meteor'?|Are you sure you identified the right module?",
        "+w,|Ivy Rene, you claim that the first module name that appeared was Painting, correct?",
        "-w,|What do you mean \"I claim\"? I know it was Painting! No other modules at the time of release would work...",
        "+wX13|Agh! You got a point there...",
        "+w,|You claim you were looking at Mssngv Wls, if I recall correctly. However I'm certain you were looking at--",
        "-w,|What are you talking about? Despite your name, you likely are not aware that Only Connect has 2 stages.",
        "+wX13|Wait, what?!",
        "+w.|Ah, I see what you must've gotten wrong. You claim that the second module name was Meteor, correct?",
        "-w.|Yep, that's what came to mind.",
        "+w.|I know for certain that what appeared could not have been Meteor.",
        "-w.|Wait, how so?",
        "+w.|The manual for Mssngv Wls states that the module shows the name of a module released before March 2021. ",
        "-w.|Wait a minute...",
        "+w.|Where you can clearly see that Meteor was released in April of that year, meaning it is not included.",
        "-w.|Ah shoot, the module was Meter, wasn't it... darn.",
        "+w!|I can confirm the only module it could have been was Meter."
    };
    public static string[] Case1 = {
        "ROB|1",
        "-w.|Hey Mr. Edgework!",
        "+b_02|(ROB is nice, almost too nice. I wonder what he wants.)|w|p|What's up?",
        "+w.|Hey ROB, nice to see you.",
        "-w.|Um I've got a question for you...",
        "+w.|Oh, you do?",
        "-w.|Yeah I was on Twitch Plays a while ago and everyone got mad at me for blowing up the bomb.",
        "*w.|I'm sorry to hear that, but that's not a question.",
        "-w_1108|Oh my bad, can I ask you how I struck on Round Keypad?|br|nq|Of course I can!|Round Keypad doesn't exist.",
        "*w,|ROB, I'm pretty sure there's no such thing as Round Keypad.",
        "-w,|Have you been living under a rock, Edgework? That module has been out for years!",
        "*bX11|(How have I been bested by the Banana guy?!)",
        "*w.|What happened that caused the strike to occur?",
        "-w.|Aight, so the symbols were forward Charlie, loop-de-loop, both hollow and filled stars, Omega, Lambda...",
        "-w.|...upside-down question mark, and my personal favorite, the smiley face.",
        "*w.|Okay, we now know what's on the module, what did you do then?",
        "-w.|I noticed that the 2nd, 3rd, and 5th columns were tied.",
        "-w.|I used that rule in the manual and sent a command which pressed seven buttons.",
        "-w.|Then the bomb blew up, and I don't know why.",
        "*b_261922|(Hmmm... where did ROB go wrong?)|bbb|rbp|The column used was incorrect.|Those symbols are from the wrong module.|I think you missed a symbol.",
        "*w,|Those symbols you read out, they don't appear to be from Round Keypad.",
        "-w,|Did you even LOOK at the manual you dunce?",
        "*wX18|What on earth was I thinking?!",
        "*w,|I think you missed a symbol on the keypad.",
        "-w,|I don't think I did, but let's count them!",
        "-w,|1, 2, 3, 4, 5, 6, 7... 8. There are 8 symbols, dude.",
        "*bX18|(Round Keypad is a lot harder that I thought...!)",
        "*w.|Ah, I see what happened. You excluded the symbols from the wrong column.",
        "-w.|Wait, what?",
        "*w.|When it says \"right-most column\" in the manual, it means the rightmost of the TIED columns.",
        "-w.|Y'know what now that you said it out loud that makes a lot more sense, thanks!",
        "*w.|Happy to help, ROB.",
        "*b!|(That manual is somewhat ambiguous but it's so old I think we'll cut the manual some slack...)"
    };
    public static string[] Case2 = {
        "Kokoro|4",
        "-w_01|Yo.|w|p|What's up?",
        "*w.|How's it going?",
        "-w.|Not that well to be honest, we had to get rid of a really good bomb attempt after missing a Forget Me Not stage.",
        "*b.|(Missing a Forget Me Not stage? This is quite unusual given how often he defuses.)",
        "-w_0805|And I have absolutely no idea how I skipped a stage.|br|nr|I'll help you figure it out.|Who cares.",
        "*w,|Eh, who cares? It's not likely you'll run into that again.",
        "-w,|I'm sorry but last time I checked, missing a stage is unacceptable. I must figure out what went wrong.",
        "*bX08|(I can't let Edgework's family name be associated with my stupidity...!)",
        "*w.|Alright, let's take a look at the logfile...",
        "-w.|It says we also had an IPA, Splitting the Loot, The Heart, Silenced Simon, Stained Glass, Logic Gates...",
        "*w.|That is... a selection of modules.",
        "-w.|...and that's it really.",
        "*b_131721|(Must've been one of the bombs in an endurance run. At least there's not many possibilities.)|bbb|bqr|You had an ignored module on the bomb.|Are you sure it wasn't Forget Us Not?|A module solved without your knowledge.",
        "*w,|Ah, I see. You had an ignored module on the bomb.",
        "-w,|Uhhh, you sure? I'm fairly certain none of them are ignored but feel free to check.",
        "*b,|(Okay, let's take a look...)",
        "*bX12|(...darn. he's right. None of these are ignored.)",
        "*w,|Hmmm, I think the only possible option is that the Forget Me Not was actually a Forget Us Not.",
        "-w,|Are you kidding? You really thought that I'd mix the two up?!",
        "*w,|Uh... yeah I was kidding!",
        "*bX12|(...he's not falling for that one is he.)",
        "*w.|Ah, I know. A module must've solved without you realizing it.",
        "-w.|And what would that be, Edgework?",
        "*w.|The Heart. Yeah it's one of those pseudo-needies that isn't ignored by bosses.",
        "-w.|Ah, yeah that makes a lot of sense.",
        "*w.|Happy to help!",
        "-w!|I'll make sure to keep an eye on The Heart next time."
    };

    public static string[] Case3 = {
        "Interpret|2",
        "*b.|(Oh, it's Mr. Interpret.)",
        "-w_02|Hi, Mr. Edgework. Can I ask you about something that happened to me recently?|w|p|Of course!",
        "*w.|Sure, what ended up happening?",
        "-w.|So, me and my friends were doing a random freeplay bomb, we hadn't done those in a while.",
        "*b.|(Now that you bring it up I haven't done a freeplay bomb in a long time...)",
        "-w_0906|We had a Keypad Directionality module on the bomb. Do you know that module, Edgework?|br|bn|Yes, I do know Keypad Directionality.|No, I don't.",
        "*w.|No, I don't.",
        "-w.|Oh, that's fine. Luckily the manual isn't that long.",
        "*b.|(The first page is full of text, that being said though I've read worse.)",
        "*w.|Uh, yeah I know Keypad Directionality. But what happened exactly?",
        "-w.|Oh, right. Sorry. I'm fairly certain I got every single stage wrong...",
        "*w.|All of them? Interesting...",
        "-w.|The first stage should be enough to figure out what I messed up, right?",
        "*w.|I mean it's all the data you have, right?",
        "-w.|How'd you know?",
        "-w.|Anyway the starting number was 5, and the directions were up, up-right, up-left, down.",
        "-w.|And I got 8352 as the answer for that stage.",
        "*w.|Ah, okay. I see what happened.",
        "-w_271922|You do? Well if so what number should have been the answer?|bbb|bqr|2958|8152|2318",
        "*w,|I believe it would be 8152.",
        "-w,|That doesn't sound right, it's very similar to my answer.",
        "*bX18|(Looks like I made the same mistake!)",
        "*w,|It has to be 2318.",
        "-w,|I... don't see how that can possibly be right.",
        "*w,|Oh?",
        "-w,|Yeah you have to move across the keypad in those directions.",
        "*wX18|Oh... you're right. Darn.",
        "*w.|Ah, I know the answer. But before I answer your question, may I ask you a question?",
        "-w.|Uhhh... sure.",
        "*w.|Were you looking down at your keyboard when you were experting this?",
        "-w.|I don't see how that matters but yeah, I was.",
        "*w.|As you can see in the top-right image of the module, the numbers on the keypad are in order...",
        "*w.|...and those that are on your keyboard are vertically flipped.",
        "-w.|Oh, okay. I'll write a note saying not to look down at my keyboard when I do this.",
        "*b!|(He doesn't need to look down at the keyboard much to begin with.)"
    };

    public static string[] Case4 = {
        "Min|6",
        "*w.|Hello there.",
        "-w_02|Oh hey, I've heard of you before. You're Mr. Edgework, right?|w|p|Indeed I am.",
        "*w.|Yes I am, nice to meet you. Do you need me for something?",
        "-w.|Yeah actually, isn't it your job to help figure out stuff?",
        "*w.|Pretty much, yeah.",
        "-w.|Can you figure out why I blew up the bomb to Ice Cream?",
        "*w.|Of course I can, I'm very familiar with Ice Cream.",
        "*b_1208|(Both the module and the food, ice cream is delicious. Let's not think about the food too much though.)|br|nk|Can you tell me what happened?|I'm gonna go get some ice cream.",
        "*w,|Y'know what this talk about ice cream makes me really want some. You mind if I get some?",
        "-w,|Now's not the time for clowning around, Edgework.",
        "*w,|Ah yeah, sorry.",
        "*bX12|(He's got a point. Didn't I just say not to think about the food too much?)",
        "*w.|Can you tell me the details?",
        "-w.|Sure, first things first, we were on the last stage, but we only had just over a minute left so we had to hurry.",
        "-w.|The last digit of the Serial Number was a 2, and the customer was Simon. Meaning allergies are \"1-6-4\".",
        "*w.|And what does that mean exactly?",
        "-w.|That means we can't give Simon strawberry, cookies, or fruit flavors. ",
        "*w.|Alright, go on.",
        "-w.|We had more unlit indicators than lit, so it's not the first list, however we do have an empty port plate.",
        "*w.|Okay, so the second list is used.",
        "-w.|For flavors on the module, we have Tutti Frutti, Raspberry Ripple, Double Strawberry, The Classic, and--",
        "*w.|You can stop there, I know the last one's Vanilla.",
        "-w_233227|Okay well the fact remains that Vanilla was the wrong answer. But I don't see how that can be.|bbb|nbr|You had the wrong allergies.|You submitted on an odd minute.|You gave Simon the wrong flavor.",
        "*w,|Ah, I see, you got the allergies wrong.",
        "-w,|Uh, really?",
        "*w,|According to info you gave me, the intersection of 2 and Simon in the table is... \"1-6-4\".",
        "*bX22|(Exactly what he gave me, darn.)",
        "*w,|It's quite simple: Vanilla was incorrect.",
        "-w,|Then what flavor could it have possibly been?",
        "*w,|Let's see... No fruit. Oh wait a minute...",
        "-w,|They all have fruit dude.",
        "*wX22|Gahh!",
        "*w.|Oh, I see. It's a very common mistake. You submitted on an odd minute.",
        "-w.|Ah wait... I did.",
        "*w.|The manual states \"Selling ice cream on an odd-numbered minute causes a strike.\"",
        "-w.|I don't think you need to rub in it like that, I already read the manual.",
        "*w.|Whoops, that wasn't what I intended. I apologize.",
        "-w!|It's alright."
    };

    public static string[] Case5 = {
        "Zebe|5",
        "-w_01|He-- Hello?|w|p|Hello.",
        "*w.|Hi there, how's it going?",
        "-w.|I've been doing well... mostly.",
        "*w.|Mostly?",
        "-w.|I recently got a strike on Two Bits.",
        "*w.|Luckily for you Two Bits is one of my favorites, I can help you sort this out.",
        "-w.|How'd you figure out that I didn't know how I struck?",
        "*w.|Well, if you knew why you struck you wouldn't be asking me, now would you?",
        "-w_0920|Yeah, right.|br|kq|Tell me what you did.|Let me just guess what happened.",
        "*w.|Can you tell me exactly what occurred?",
        "-w.|Sure thing, sir.",
        "-w.|Edgework was 3 batteries in 3 holders, unlit CAR, and RCA on one plate...",
        "-w.|...Serial Number was ZK7LW0.",
        "*w.|Yep, go on...",
        "-w.|I then went on to do Charlie Victor query.",
        "-w.|That gave me 19, so Papa Tango query.",
        "-w.|Then we got 32, and that's Kilo Zulu query.",
        "-w.|And finally 99, which is Delta Charlie submit.",
        "-w.|After that noise, well, you already know what happened.",
        "*b.|(I know that noise all too well.)",
        "*w_212429|Alright, let's see if I can see where you went wrong.|bbb|prb|You queried an incorrect number of times.|You mixed up rows and columns in the table.|You had the wrong starting number.",
        "*w,|Ah, I know. You queried an incorrect number of times.",
        "-w,|Edgework, were you even listening? I clearly queried 3 times.",
        "*wX20|Agh! Well that wasn't it.",
        "*w,|Do you think you mixed up the rows and columns in the table?",
        "-w,|...",
        "*w,|...",
        "-w,|That's one of the most ridiculous things I've ever heard.",
        "*bX20|(I didn't mean to insult him.)",
        "*w.|Oh, I see what happened. You had the wrong starting number.",
        "-w.|How exactly did that happen?",
        "*w.|You said you had an RCA port, correct?",
        "-w.|Yeah, I did say that.",
        "*w.|The manual says if you have an RCA port, to double your starting number.",
        "-w.|Oh, okay. Yeah that would explain how I got it wrong. Thanks!",
        "*w!|No problemo."
    };

    public static string[] Case6 = {
        "Well|3",
        "-w_01|Hello Mr. Edgework.|w|p|Hey there, how's it going?",
        "*w.|Hey there, how's it going?",
        "-w.|Last night a Morsematics strike blew up the bomb.",
        "*b.|(Morsematics, huh? That's one of the most common places to get a strike.)",
        "*w.|Yeah, I'll help you figure out what you did wrong.",
        "-w.|Where do we even begin though?",
        "*b_1207|(That is a good question, where do we begin?)|br|nq|Are you sure you got your inputs correct?|I know you got your inputs wrong.",
        "*w,|I know exactly what happened!",
        "-w,|Do you?",
        "*w,|Yeah, you got your inputs wrong.",
        "-w,|Can you at least let me speak before you make an accusation like that?",
        "*bX06|(I had a feeling that was wrong...)",
        "*w.|Are you sure you got your inputs right? That part is quite tricky.",
        "-w.|Okay, so my final answer was X-ray, which is dash dot dot dash.",
        "-w.|I do very long dashes, medium sized gaps and very small dots. That seems to work for me.",
        "*w.|Alright, you probably got that right. Can you go through the solve itself?",
        "-w.|Of course I can.",
        "-w.|My Morse letters were Oscar, Uniform, and Kilo.",
        "-w.|My Serial Number characters were Papa and Tango.",
        "-w.|I had no indicators so the first rule could not apply.",
        "-w.|Papa is 16, and Tango is 20, added together is 36. Which is 6 squared, so add 4 to A, it's now Tango.",
        "-w.|Adding the largest received letter, Uniform to A, makes A 15, which is Oscar.",
        "-w.|Next rule is subtracting prime letters from A.",
        "-w.|Oscar and Uniform aren't prime, but Kilo is prime. A - 11 = 4, which makes A Delta.",
        "-w.|None of the three letters are squares, obviously, and I had no batteries so the last rule does nothing.",
        "*b.|(No batteries and indicators? That's a strange bomb...)",
        "-w.|B is more than A, so adding A and B, that's 4 + 20, which is 24. X-ray should've been the answer.",
        "*w_342831|Alright, now that I've heard all that...|bbb|rnb|Are you sure 36 is square?|Uniform wasn't the largest letter.|Kilo wasn't the only prime letter.",
        "*w,|...Uniform wasn't the largest letter on the module.",
        "-w,|Do you need to go back to first grade, Edgework? The other letters were Kilo and Oscar.",
        "*wX27|What on Earth was I thinking?!",
        "*w,|...Kilo wasn't the only prime letter on the module.",
        "-w,|That's not right, Oscar is 15 which is divisible by 5. Uniform is 21 which is divisible by 3.",
        "*bX27|(Have I actually gone insane?!)",
        "*w.|...You forgot to keep numbers between 1 and 26.",
        "-w.|Oh?",
        "*w.|You stated earlier that Papa + Tango is 36, but you should've subtracted 26 before checking if it's a square.",
        "-w.|Ah, I see now.",
        "*w!|People make that mistake all the time."
    };

    public static string[] Case7 = {
        "West|7",
        "*w.|Woah, is that who I think it is?!",
        "-w_02|Yes, it is who you think it is.|w|n|What do you need?",
        "*w.|Mr. West, how can I help you?",
        "-w_0804|I'll just get straight to the point: I struck on Yellow Arrows. Can you help me?|br|pq|Didn't I just say yes?|I don't help celebrities.",
        "*w,|I'm sorry sir but I don't think I can help you.",
        "-w,|Very well, let me get my business card.",
        "*b,|(Wait, what?!)",
        "*wX08|Lemme read that thing... okay yeah I need to do this don't I, sorry sir!",
        "*w.|Tell me about what happened.",
        "-w.|The display had a Yankee on it, which means to use the rule in the Yankee row.",
        "-w.|\"Press any if up hasn't been pressed yet\", which it has not. So I can press whatever.",
        "-w.|The last digit in the Serial Number is a 5, which means I need to go down 6 rows, I didn't forget to add 1.",
        "-w.|That leads me to the Echo row. \"Press right if lit SIG is present.\" Which there was on the bomb, so right.",
        "*w.|Understood, continue...",
        "-w.|Plus 6 from Echo is Kilo: \"Down if 9 is an odd number.\" Is 9 odd, Edgework?",
        "*w.|...yes.",
        "-w.|So that means the next press is down. After that is the Quebec rule.",
        "-w.|\"Down if previous input was right...\" Which is not true, \"...otherwise left.\" So next is left.",
        "-w.|And finally the Whiskey rule. \"Right if no port plates are present.\" There were port plates on the bomb.",
        "-w.|\"Otherwise left.\" Which means that down, right, down, left, left is an acceptable sequence. But it wasn't.",
        "*w_212528|Alright, I think I see what you did.|bbb|rkb|You're not supposed to add 1 to 5.|You are incapible of adding 6 to letters.|You don't use the starting row's rule.",
        "*w,|What gave you the idea to add 1 to 5 like that?",
        "-w,|\"Then, take the last digit of the Serial Number plus one, and move down that many rows.\"",
        "-w,|That did say \"plus one\", did it not?",
        "*wX20|Argh! It did!",
        "*w,|I believe you messed up one of the plus 6s.",
        "-w,|Then I'll just say letters in groups of 6. Yankee... ZABCD.. Echo, FGHIJ.. Kilo, LMNOP.. Quebec, RSTUV.. Whiskey. ",
        "*bX20|(How is Kanye smarter than me???)",
        "*w.|Oh, I see. You used the rule in the starting row when you weren't supposed to.",
        "-w.|Wait, what?",
        "*w.|It says to move down however many rows before you apply any rules.",
        "-w.|Ah okay that makes sense, I'll likely come back here for any other inquiries regarding modules.",
        "*b!|(Sounding so professional... I should try that.)"
    };

    public static string[] Case8 = {
        "Wiohgi|8",
        "*b.|(Hmmm what do I do-- wait a minute, is that banging on my door?)",
        "*w.|COME ON IN!!!",
        "-w.|Hello sir, we're in an emergency.",
        "*w.|An emergency?",
        "-w.|We're mid-bomb and LED Encryption has no correct answer.",
        "*w_06|Oh, okay! Let's not waste any time then!|w|q|Give me the read.",
        "*w.|What is the read?",
        "-w.|First stage color is red. Oscar, Tango, Zulu and Uniform are your letters.",
        "-w.|15x2=30, minus 26 is 4, not 21. 20x2=40, turns into 14 which isn't 26...",
        "-w_1013|...26x2=52, minus 26 is definitely not 20. 21x2=42, minus 26 is 16 which isn't 15! Nothing works!|bb|nb|Press Oscar.|Press Uniform.",
        "*w,|Okay, press Oscar.",
        "-w,|...that gave us a strike!",
        "*wX09|Crap!",
        "*w.|Press Uniform.",
        "-w_211518|Okay, that worked. Can you tell me what I did wrong so I can do the rest?|bbb|kpr|Numbers are 0-indexed.|You multiplied by the wrong number.|You're not supposed to multiply.",
        "*w,|You weren't supposed to multiply by 2.",
        "-w,|What do you mean it says 2 under red in the table...",
        "*wX14|Whyyyy...",
        "*w,|You don't multiply in this module.",
        "-w,|That is just not right, I think I might've banged on the wrong person's door.",
        "*wX14|I'm sorryyyyy!",
        "*w.|Alpha is 0 on this module, not 1.",
        "-w.|Wait, really?",
        "*w.|Yes, and Bravo's 1, Charlie's 2, you get the idea.",
        "-w.|Okay it says we completed the bomb in 17 minutes and 41 seconds.",
        "*b!|(Wait a minute, does that mean the bomb was in Zen mode?)"
    };
}
